# Generated by Django 5.2 on 2025-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tickets',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
