# Generated by Django 5.2 on 2025-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_remove_booking_tickets_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
